name: 1851_QA_Development

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: |
        yarn install

    - name: Run Playwright tests
      id: playwright-tests
      run: yarn playwright test
      continue-on-error: true

    - name: Set Playwright test status
      id: set-playwright-status
      run: |
        if [ ${{ steps.playwright-tests.outcome }} == "success" ]; then
          echo "playwright-color=#36a64f" >> $GITHUB_OUTPUT
          echo "playwright-title=Playwright Tests Passed" >> $GITHUB_OUTPUT
          echo "playwright-emoji=:white_check_mark:" >> $GITHUB_OUTPUT
        else
          echo "playwright-color=#ff0000" >> $GITHUB_OUTPUT
          echo "playwright-title=Playwright Tests Failed" >> $GITHUB_OUTPUT
          echo "playwright-emoji=:x:" >> $GITHUB_OUTPUT
        fi

    - name: Post to Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.26.0
      if: always()
      with:
        channel-id: 'test-slack'
        payload: |
            {
              "text": "*1851_QA_DEV Test Results*",
              "attachments": [
                {
                  "color": "${{ steps.set-playwright-status.outputs.playwright-color }}",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${{ steps.set-playwright-status.outputs.playwright-emoji }} *${{ steps.set-playwright-status.outputs.playwright-title }}*"
                      }
                    },
                    {
                      "type": "context",
                      "elements": [
                        {
                          "type": "mrkdwn",
                          "text": "Test Completed"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
      env:   
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    - name: Fail Pipeline if Tests Failed
      if: steps.playwright-tests.outcome != 'success'
      run: exit 1
