name: 1851_QA_Development

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies and Set Up Allure
      run: |
        yarn install
        yarn add -D allure-commandline
        echo "PATH=$PATH:$(pwd)/node_modules/.bin" >> $GITHUB_ENV
    
    - name: Install Dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libnspr4
          yarn playwright install-deps
          yarn playwright install chromium
    
    - name: Verify Installation
      run: |
        node -v
        yarn -v
        yarn list --depth=0  # Lists top-level packages installed
        yarn playwright --version  # Verifies Playwright version installed
        chromium --version  # Ensures Chromium is installed

    - name: Run Tests (Simulated)
      id: run-tests
      run: |
        echo "Simulating test results..."
        echo "0" > test-result.txt
        echo "test_exit_code=$(cat test-result.txt)" >> $GITHUB_ENV

    - name: Set Test Status
      id: set-test-status
      run: |
        if [[ ${{ env.test_exit_code }} == "0" ]]; then
          echo "color=#36a64f" >> $GITHUB_ENV
          echo "title=Tests Passed" >> $GITHUB_ENV
          echo "emoji=:white_check_mark:" >> $GITHUB_ENV
          echo "status=Tests Passed" >> $GITHUB_ENV
        else
          echo "color=#ff0000" >> $GITHUB_ENV
          echo "title=Tests Failed" >> $GITHUB_ENV
          echo "emoji=:x:" >> $GITHUB_ENV
          echo "status=Tests Failed" >> $GITHUB_ENV
        fi

    - name: Post to Slack Channel
      uses: slackapi/slack-github-action@v1.26.0
      with:
          channel-id: 'test-slack'
          payload: | 
            {
              "text": "*1851_QA_DEV_TEST*\nThis is a test message for Playwright Test Status.",
              "attachments": [
                {
                  "color": "${{ env.color }}",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${{ env.emoji }} *${{ env.status }}*"
                      }
                    },
                    {
                      "type": "context",
                      "elements": [
                        {
                          "type": "mrkdwn",
                          "text": "Test Completed"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    - name: Fail Pipeline if Tests Failed
      run: |
        if [[ ${{ env.test_exit_code }} != "0" ]]; then
          exit 1
        fi
