name: Slack Notification Test
on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Post to Slack Channel - Test
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'test-slack'
          payload: |
            {
              "text": "*Test Slack Notification*\nThis is a test message from my GitHub Action.",
              "attachments": [
                {
                  "color": "#36a64f",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": ":white_check_mark: *Test Message*"
                      }
                    },
                    {
                      "type": "context",
                      "elements": [
                        {
                          "type": "mrkdwn",
                          "text": "Test completed successfully"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
